// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3NfPPfKu3shqHD5A8QxQqJQN1oII9CwA',
    appId: '1:911494650896:web:d99e086f55d1f2edb23e95',
    messagingSenderId: '911494650896',
    projectId: 'reddit-clone-2022',
    authDomain: 'reddit-clone-2022.firebaseapp.com',
    storageBucket: 'reddit-clone-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzUf-0MzRx3soEiGDM6cF0DjRa3mGdxoY',
    appId: '1:911494650896:android:16e3c97a075ababfb23e95',
    messagingSenderId: '911494650896',
    projectId: 'reddit-clone-2022',
    storageBucket: 'reddit-clone-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxfZTsZDTnvrfe6BE5ZCH-KOwcgy7_xI8',
    appId: '1:911494650896:ios:b36c184ed271fcb5b23e95',
    messagingSenderId: '911494650896',
    projectId: 'reddit-clone-2022',
    storageBucket: 'reddit-clone-2022.appspot.com',
    iosClientId:
        '911494650896-0qglja4s4930f1tn8o4p58fmto2dphu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
